<?php


namespace app\user\controller;


use app\user\BaseController\Rece;
use think\Session;

class Admin extends Rece
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!Session::get('user_info')) $this->redirect('index/index');
    }

    public function index()
    {
        return $this->fetch();
    }
}